export type PhotoSealDocumentationRuntimeSmokeStatus = "PASS" | "FAIL" | "NOT_RUN";

export type PhotoSealDocumentationRuntimeSmokeReason =
  | "OK"
  | "NO_BROWSER_RUNNER"
  | "PLAYWRIGHT_NOT_INSTALLED"
  | "BROWSER_LAUNCH_UNAVAILABLE"
  | "NO_VITE_DEV_SERVER"
  | "APP_LOAD_FAILED"
  | "DOCUMENTATION_SMOKE_HOOK_MISSING"
  | "DOCUMENTATION_COMPONENT_UNAVAILABLE"
  | "CLIPBOARD_RUNTIME_UNAVAILABLE"
  | "DOCUMENTATION_PANEL_RENDER_FAILED"
  | "INSTITUTION_NOTE_COPY_RENDER_FAILED"
  | "DISCLAIMER_BADGE_MISSING"
  | "INSTITUTION_NOTE_COPY_MISSING"
  | "COPY_BUTTON_MISSING"
  | "CLIPBOARD_FALSE_SUCCESS_DETECTED"
  | "COPY_STATUS_ARIA_LIVE_MISSING"
  | "OVERCLAIM_DETECTED"
  | "DISCLAIMER_NOT_VISIBLE"
  | "RUNTIME_RECEIPT_WRITE_FAILED";

export type PhotoSealClipboardProbeStatus = "copied" | "failed" | "unsupported";
